# Generated by Django 3.2.6 on 2022-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
