# Generated by Django 3.2.6 on 2022-07-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='fname',
            new_name='group',
        ),
    ]
