# Generated by Django 3.2.6 on 2022-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220727_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='department',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='fname',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='program',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='mname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mname',
        ),
        migrations.AddField(
            model_name='advisor',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
